export const data = [
  {
    id: 1,
    name: "Barbell Bench Press",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Chest",
  },
  {
    id: 2,
    name: "Incline Dumbbell Press",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Chest",
  },
  {
    id: 3,
    name: "Push-Up",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Chest",
  },
  {
    id: 4,
    name: "Pull-Up",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Back",
  },
  {
    id: 5,
    name: "Bent-Over Row",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Back",
  },
  {
    id: 6,
    name: "Deadlift",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Back",
  },
  {
    id: 7,
    name: "Bicep Curl",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Biceps",
  },
  {
    id: 8,
    name: "Hammer Curl",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Biceps",
  },
  {
    id: 9,
    name: "Tricep Dip",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Triceps",
  },
  {
    id: 10,
    name: "Skull Crusher",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Triceps",
  },
  {
    id: 11,
    name: "Squat",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Quadriceps",
  },
  {
    id: 12,
    name: "Leg Press",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Quadriceps",
  },
  {
    id: 13,
    name: "Lunge",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Quadriceps",
  },
  {
    id: 14,
    name: "Leg Curl",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Hamstrings",
  },
  {
    id: 15,
    name: "Romanian Deadlift",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Hamstrings",
  },
  {
    id: 16,
    name: "Leg Extension",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Quadriceps",
  },
  {
    id: 17,
    name: "Calf Raise",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Calves",
  },
  {
    id: 18,
    name: "Shoulder Press",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Shoulders",
  },
  {
    id: 19,
    name: "Lateral Raise",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Shoulders",
  },
  {
    id: 20,
    name: "Front Raise",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Shoulders",
  },
  {
    id: 21,
    name: "Plank",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Core",
  },
  {
    id: 22,
    name: "Russian Twist",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Core",
  },
  {
    id: 23,
    name: "Crunch",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Core",
  },
  {
    id: 24,
    name: "Hanging Leg Raise",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Core",
  },
  {
    id: 25,
    name: "Cable Fly",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Chest",
  },
  {
    id: 26,
    name: "Pec Deck Machine",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Chest",
  },
  {
    id: 27,
    name: "Chest Dip",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Chest",
  },
  {
    id: 28,
    name: "Reverse Fly",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Back",
  },
  {
    id: 29,
    name: "Seated Row",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Back",
  },
  {
    id: 30,
    name: "Lat Pulldown",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Back",
  },
  {
    id: 31,
    name: "Face Pull",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Back",
  },
  {
    id: 32,
    name: "Overhead Tricep Extension",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Triceps",
  },
  {
    id: 33,
    name: "Close-Grip Bench Press",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Triceps",
  },
  {
    id: 34,
    name: "Preacher Curl",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Biceps",
  },
  {
    id: 35,
    name: "Concentration Curl",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Biceps",
  },
  {
    id: 36,
    name: "Standing Calf Raise",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Calves",
  },
  {
    id: 37,
    name: "Seated Calf Raise",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Calves",
  },
  {
    id: 38,
    name: "Shrug",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Trapezius",
  },
  {
    id: 39,
    name: "Arnold Press",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Shoulders",
  },
  {
    id: 40,
    name: "Farmer's Walk",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Forearms",
  },
  {
    id: 41,
    name: "Forearm Curl",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Forearms",
  },
  {
    id: 42,
    name: "Reverse Forearm Curl",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Forearms",
  },
  {
    id: 43,
    name: "Leg Raise",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Core",
  },
  {
    id: 44,
    name: "Side Plank",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Core",
  },
  {
    id: 45,
    name: "Mountain Climber",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Core",
  },
  {
    id: 46,
    name: "Hip Thrust",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Glutes",
  },
  {
    id: 47,
    name: "Glute Bridge",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Glutes",
  },
  {
    id: 48,
    name: "Bulgarian Split Squat",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Quadriceps",
  },
  {
    id: 49,
    name: "Cable Crunch",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Core",
  },
  {
    id: 50,
    name: "Cable Lateral Raise",
    image: "https://picsum.photos/1",
    video: "https://picsum.photos/1",
    target_muscle: "Shoulders",
  },
];
